### PR TITLE
Handle flat JSON escape dot syntax

### PR DESCRIPTION
**Pull request by gquittet**
The goal is to support this kind of JSON

```json
{"firstName.lastName": "Guillaume"}
```

using this rule:

```json
{"===": [{"var": "firstName\\.lastName"}, "Guillaume"]}
```

It's already implemented in the `json-logic-engine`: https://github.com/TotalTechGeek/json-logic-engine
See:
* https://github.com/TotalTechGeek/json-logic-engine/issues/23
* https://github.com/TotalTechGeek/json-logic-engine/pull/24

I already made the code for you but I'm not a Rust developer so feel free to edit the code as you wish 😉 

I tested my code using the following Python code:

```python
import jsonlogic_rs


def main() -> None:
    schema = {"===": [{"var": "firstName\\.lastName"}, "Guillaume"]}
    data = {"firstName.lastName": "Guillaume"}
    assert jsonlogic_rs.apply(schema, data) is True


if __name__ == "__main__":
    main()
```

### CODE REVIEW

**Comment by gquittet** [comment]
Hello @jstewmon @mplanchard 👋

Can you look at it when you have time? 👀

Thank you very much! 🙏

**Comment by gquittet** [comment]
I also tested it using this code and it's also working great!

```python
import jsonlogic_rs


def main() -> None:
    schema = {
        "or": [
            {"===": [{"var": "a\\.b"}, "Guillaume"]},
            {"===": [{"var": "a\\.b.Name"}, "Guillaume"]},
        ]
    }
    data1 = {"a.b": "Guillaume"}
    data2 = {"a.b": {"Name": "Guillaume"}}
    assert jsonlogic_rs.apply(schema, data1) is True
    assert jsonlogic_rs.apply(schema, data2) is True


if __name__ == "__main__":
    main()

```

**Comment by gquittet** [comment]
Hello @jstewmon and @mplanchard 👋 

Can you look at this pull request when you have time? 👀 

Thank you! 🤟

**Comment by gquittet** [comment]
Hello @jstewmon and @mplanchard 👋 

Can you look at this pull request when you have time? 👀 

Thank you! 🤟 

I'm using this version in prod since 1 month and everything is running fine 💪

Is it possible to be a co-maintainer to be able to update to project with new Python version and to help you to review + merge incoming pull requests?

**Review by jstewmon — CHANGES_REQUESTED** [review]
I think if we want to use `\` as an escape character, the solution should be a little more robust.

For example, a key whose unescaped value is `foo\.bar` should be supported. The JSON value for `foo\.bar` would be `"foo\\\\\\\\\\\\.bar"` 😵‍💫 .

Here's a set of test cases we should add (expressed as unescaped values):
```
foo\.bar => [foo.bar]
foo\\.bar => [foo\, bar]
foo\\\.bar => [foo\.bar]
foo\\bar => [foo\bar]
```

I asked Copilot "rust function to split a string by a character, using backslash as escape character", and it suggested the following:
```rust
pub fn split_with_escape(input: &str, delimiter: char) -> Vec<String> {
    let mut result = Vec::new();
    let mut current = String::new();
    let mut escape = false;

    for c in input.chars() {
        if escape {
            current.push(c);
            escape = false;
        } else if c == '\\' {
            escape = true;
        } else if c == delimiter {
            result.push(current.clone());
            current.clear();
        } else {
            current.push(c);
        }
    }

    if !current.is_empty() {
        result.push(current);
    }

    result
}
```

The Copilot suggestion LGTM if you'd like to use it to amend your PR.

**Comment by gquittet** [comment]
@jstewmon 

Great idea! 💡

I just implemented it and I added some unit tests. Thanks for the review! 🤟

**Pull request merged**
